spring:
  liquibase:
    change-log: classpath:config/liquibase/master.xml
    contexts: schema
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/users}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
security:
  authentication:
    jwt:
      secret: br8dMKkzJk9Y5QPcYbBGcKngJtC3cdGK4sJwuzgc
      # 24 hours
      token-validity-in-seconds: 360000
server:
  port: 8082